package model;
// Generated 07/10/2017 10:54:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaFuncionario generated by hbm2java
 */
@Entity
@Table(name="ta_funcionario"
    ,catalog="ata_reuniao"
)
public class TaFuncionario  implements java.io.Serializable {


     private Integer idtFuncionario;
     private TbCargo tbCargo;
     private TbEmpresa tbEmpresa;
     private TbPessoa tbPessoa;
     private TbSetor tbSetor;
     private boolean flgAtivo;
     private String lgnFuncionario;
     private String pswFuncionario;
     private Set<TaParticipantes> taParticipanteses = new HashSet<TaParticipantes>(0);

    public TaFuncionario() {
    }

	
    public TaFuncionario(TbCargo tbCargo, TbEmpresa tbEmpresa, TbPessoa tbPessoa, TbSetor tbSetor, boolean flgAtivo, String lgnFuncionario, String pswFuncionario) {
        this.tbCargo = tbCargo;
        this.tbEmpresa = tbEmpresa;
        this.tbPessoa = tbPessoa;
        this.tbSetor = tbSetor;
        this.flgAtivo = flgAtivo;
        this.lgnFuncionario = lgnFuncionario;
        this.pswFuncionario = pswFuncionario;
    }
    public TaFuncionario(TbCargo tbCargo, TbEmpresa tbEmpresa, TbPessoa tbPessoa, TbSetor tbSetor, boolean flgAtivo, String lgnFuncionario, String pswFuncionario, Set<TaParticipantes> taParticipanteses) {
       this.tbCargo = tbCargo;
       this.tbEmpresa = tbEmpresa;
       this.tbPessoa = tbPessoa;
       this.tbSetor = tbSetor;
       this.flgAtivo = flgAtivo;
       this.lgnFuncionario = lgnFuncionario;
       this.pswFuncionario = pswFuncionario;
       this.taParticipanteses = taParticipanteses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_funcionario", unique=true, nullable=false)
    public Integer getIdtFuncionario() {
        return this.idtFuncionario;
    }
    
    public void setIdtFuncionario(Integer idtFuncionario) {
        this.idtFuncionario = idtFuncionario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_cargo", nullable=false)
    public TbCargo getTbCargo() {
        return this.tbCargo;
    }
    
    public void setTbCargo(TbCargo tbCargo) {
        this.tbCargo = tbCargo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_empresa", nullable=false)
    public TbEmpresa getTbEmpresa() {
        return this.tbEmpresa;
    }
    
    public void setTbEmpresa(TbEmpresa tbEmpresa) {
        this.tbEmpresa = tbEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_pessoa", nullable=false)
    public TbPessoa getTbPessoa() {
        return this.tbPessoa;
    }
    
    public void setTbPessoa(TbPessoa tbPessoa) {
        this.tbPessoa = tbPessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_setor", nullable=false)
    public TbSetor getTbSetor() {
        return this.tbSetor;
    }
    
    public void setTbSetor(TbSetor tbSetor) {
        this.tbSetor = tbSetor;
    }

    
    @Column(name="flg_ativo", nullable=false)
    public boolean isFlgAtivo() {
        return this.flgAtivo;
    }
    
    public void setFlgAtivo(boolean flgAtivo) {
        this.flgAtivo = flgAtivo;
    }

    
    @Column(name="lgn_funcionario", nullable=false, length=45)
    public String getLgnFuncionario() {
        return this.lgnFuncionario;
    }
    
    public void setLgnFuncionario(String lgnFuncionario) {
        this.lgnFuncionario = lgnFuncionario;
    }

    
    @Column(name="psw_funcionario", nullable=false, length=45)
    public String getPswFuncionario() {
        return this.pswFuncionario;
    }
    
    public void setPswFuncionario(String pswFuncionario) {
        this.pswFuncionario = pswFuncionario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taFuncionario")
    public Set<TaParticipantes> getTaParticipanteses() {
        return this.taParticipanteses;
    }
    
    public void setTaParticipanteses(Set<TaParticipantes> taParticipanteses) {
        this.taParticipanteses = taParticipanteses;
    }




}


