package model;
// Generated 07/10/2017 10:54:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbCargo generated by hbm2java
 */
@Entity
@Table(name="tb_cargo"
    ,catalog="ata_reuniao"
)
public class TbCargo  implements java.io.Serializable {


     private Integer idtCargo;
     private String nmeCargo;
     private boolean flgAtivo;
     private Set<TaFuncionario> taFuncionarios = new HashSet<TaFuncionario>(0);

    public TbCargo() {
    }

	
    public TbCargo(String nmeCargo, boolean flgAtivo) {
        this.nmeCargo = nmeCargo;
        this.flgAtivo = flgAtivo;
    }
    public TbCargo(String nmeCargo, boolean flgAtivo, Set<TaFuncionario> taFuncionarios) {
       this.nmeCargo = nmeCargo;
       this.flgAtivo = flgAtivo;
       this.taFuncionarios = taFuncionarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_cargo", unique=true, nullable=false)
    public Integer getIdtCargo() {
        return this.idtCargo;
    }
    
    public void setIdtCargo(Integer idtCargo) {
        this.idtCargo = idtCargo;
    }

    
    @Column(name="nme_cargo", nullable=false, length=45)
    public String getNmeCargo() {
        return this.nmeCargo;
    }
    
    public void setNmeCargo(String nmeCargo) {
        this.nmeCargo = nmeCargo;
    }

    
    @Column(name="flg_ativo", nullable=false)
    public boolean isFlgAtivo() {
        return this.flgAtivo;
    }
    
    public void setFlgAtivo(boolean flgAtivo) {
        this.flgAtivo = flgAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCargo")
    public Set<TaFuncionario> getTaFuncionarios() {
        return this.taFuncionarios;
    }
    
    public void setTaFuncionarios(Set<TaFuncionario> taFuncionarios) {
        this.taFuncionarios = taFuncionarios;
    }




}


