package model;
// Generated 07/10/2017 10:54:24 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbCompromisso generated by hbm2java
 */
@Entity
@Table(name="tb_compromisso"
    ,catalog="ata_reuniao"
)
public class TbCompromisso  implements java.io.Serializable {


     private Integer idtCompromisso;
     private TaParticipantes taParticipantes;
     private TbAssunto tbAssunto;
     private Date dtaCompromisso;
     private String dscCompromisso;

    public TbCompromisso() {
    }

    public TbCompromisso(TaParticipantes taParticipantes, TbAssunto tbAssunto, Date dtaCompromisso, String dscCompromisso) {
       this.taParticipantes = taParticipantes;
       this.tbAssunto = tbAssunto;
       this.dtaCompromisso = dtaCompromisso;
       this.dscCompromisso = dscCompromisso;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_compromisso", unique=true, nullable=false)
    public Integer getIdtCompromisso() {
        return this.idtCompromisso;
    }
    
    public void setIdtCompromisso(Integer idtCompromisso) {
        this.idtCompromisso = idtCompromisso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_part_responsavel", nullable=false)
    public TaParticipantes getTaParticipantes() {
        return this.taParticipantes;
    }
    
    public void setTaParticipantes(TaParticipantes taParticipantes) {
        this.taParticipantes = taParticipantes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_assunto", nullable=false)
    public TbAssunto getTbAssunto() {
        return this.tbAssunto;
    }
    
    public void setTbAssunto(TbAssunto tbAssunto) {
        this.tbAssunto = tbAssunto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_compromisso", nullable=false, length=10)
    public Date getDtaCompromisso() {
        return this.dtaCompromisso;
    }
    
    public void setDtaCompromisso(Date dtaCompromisso) {
        this.dtaCompromisso = dtaCompromisso;
    }

    
    @Column(name="dsc_compromisso", nullable=false, length=65535)
    public String getDscCompromisso() {
        return this.dscCompromisso;
    }
    
    public void setDscCompromisso(String dscCompromisso) {
        this.dscCompromisso = dscCompromisso;
    }




}


