package model;
// Generated 07/10/2017 10:54:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbEmpresa generated by hbm2java
 */
@Entity
@Table(name="tb_empresa"
    ,catalog="ata_reuniao"
)
public class TbEmpresa  implements java.io.Serializable {


     private Integer idtEmpresa;
     private String nmeEmpresa;
     private String cnpjEmpresa;
     private String endEmpresa;
     private String nmeAreaEmpresa;
     private String telEmpresa;
     private String emlEmpresa;
     private Set<TaFuncionario> taFuncionarios = new HashSet<TaFuncionario>(0);

    public TbEmpresa() {
    }

	
    public TbEmpresa(String nmeEmpresa, String cnpjEmpresa, String endEmpresa, String nmeAreaEmpresa, String telEmpresa, String emlEmpresa) {
        this.nmeEmpresa = nmeEmpresa;
        this.cnpjEmpresa = cnpjEmpresa;
        this.endEmpresa = endEmpresa;
        this.nmeAreaEmpresa = nmeAreaEmpresa;
        this.telEmpresa = telEmpresa;
        this.emlEmpresa = emlEmpresa;
    }
    public TbEmpresa(String nmeEmpresa, String cnpjEmpresa, String endEmpresa, String nmeAreaEmpresa, String telEmpresa, String emlEmpresa, Set<TaFuncionario> taFuncionarios) {
       this.nmeEmpresa = nmeEmpresa;
       this.cnpjEmpresa = cnpjEmpresa;
       this.endEmpresa = endEmpresa;
       this.nmeAreaEmpresa = nmeAreaEmpresa;
       this.telEmpresa = telEmpresa;
       this.emlEmpresa = emlEmpresa;
       this.taFuncionarios = taFuncionarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_empresa", unique=true, nullable=false)
    public Integer getIdtEmpresa() {
        return this.idtEmpresa;
    }
    
    public void setIdtEmpresa(Integer idtEmpresa) {
        this.idtEmpresa = idtEmpresa;
    }

    
    @Column(name="nme_empresa", nullable=false, length=45)
    public String getNmeEmpresa() {
        return this.nmeEmpresa;
    }
    
    public void setNmeEmpresa(String nmeEmpresa) {
        this.nmeEmpresa = nmeEmpresa;
    }

    
    @Column(name="cnpj_empresa", nullable=false, length=14)
    public String getCnpjEmpresa() {
        return this.cnpjEmpresa;
    }
    
    public void setCnpjEmpresa(String cnpjEmpresa) {
        this.cnpjEmpresa = cnpjEmpresa;
    }

    
    @Column(name="end_empresa", nullable=false, length=256)
    public String getEndEmpresa() {
        return this.endEmpresa;
    }
    
    public void setEndEmpresa(String endEmpresa) {
        this.endEmpresa = endEmpresa;
    }

    
    @Column(name="nme_area_empresa", nullable=false, length=45)
    public String getNmeAreaEmpresa() {
        return this.nmeAreaEmpresa;
    }
    
    public void setNmeAreaEmpresa(String nmeAreaEmpresa) {
        this.nmeAreaEmpresa = nmeAreaEmpresa;
    }

    
    @Column(name="tel_empresa", nullable=false, length=45)
    public String getTelEmpresa() {
        return this.telEmpresa;
    }
    
    public void setTelEmpresa(String telEmpresa) {
        this.telEmpresa = telEmpresa;
    }

    
    @Column(name="eml_empresa", nullable=false, length=45)
    public String getEmlEmpresa() {
        return this.emlEmpresa;
    }
    
    public void setEmlEmpresa(String emlEmpresa) {
        this.emlEmpresa = emlEmpresa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbEmpresa")
    public Set<TaFuncionario> getTaFuncionarios() {
        return this.taFuncionarios;
    }
    
    public void setTaFuncionarios(Set<TaFuncionario> taFuncionarios) {
        this.taFuncionarios = taFuncionarios;
    }




}


