package model;
// Generated 07/10/2017 10:54:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbPessoa generated by hbm2java
 */
@Entity
@Table(name="tb_pessoa"
    ,catalog="ata_reuniao"
)
public class TbPessoa  implements java.io.Serializable {


     private Integer idtPessoa;
     private String nmePessoa;
     private String telPessoa;
     private String emlPessoa;
     private String endPessoa;
     private Set<TaFuncionario> taFuncionarios = new HashSet<TaFuncionario>(0);

    public TbPessoa() {
    }

	
    public TbPessoa(String nmePessoa, String telPessoa, String emlPessoa, String endPessoa) {
        this.nmePessoa = nmePessoa;
        this.telPessoa = telPessoa;
        this.emlPessoa = emlPessoa;
        this.endPessoa = endPessoa;
    }
    public TbPessoa(String nmePessoa, String telPessoa, String emlPessoa, String endPessoa, Set<TaFuncionario> taFuncionarios) {
       this.nmePessoa = nmePessoa;
       this.telPessoa = telPessoa;
       this.emlPessoa = emlPessoa;
       this.endPessoa = endPessoa;
       this.taFuncionarios = taFuncionarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_pessoa", unique=true, nullable=false)
    public Integer getIdtPessoa() {
        return this.idtPessoa;
    }
    
    public void setIdtPessoa(Integer idtPessoa) {
        this.idtPessoa = idtPessoa;
    }

    
    @Column(name="nme_pessoa", nullable=false, length=45)
    public String getNmePessoa() {
        return this.nmePessoa;
    }
    
    public void setNmePessoa(String nmePessoa) {
        this.nmePessoa = nmePessoa;
    }

    
    @Column(name="tel_pessoa", nullable=false, length=45)
    public String getTelPessoa() {
        return this.telPessoa;
    }
    
    public void setTelPessoa(String telPessoa) {
        this.telPessoa = telPessoa;
    }

    
    @Column(name="eml_pessoa", nullable=false, length=45)
    public String getEmlPessoa() {
        return this.emlPessoa;
    }
    
    public void setEmlPessoa(String emlPessoa) {
        this.emlPessoa = emlPessoa;
    }

    
    @Column(name="end_pessoa", nullable=false, length=256)
    public String getEndPessoa() {
        return this.endPessoa;
    }
    
    public void setEndPessoa(String endPessoa) {
        this.endPessoa = endPessoa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbPessoa")
    public Set<TaFuncionario> getTaFuncionarios() {
        return this.taFuncionarios;
    }
    
    public void setTaFuncionarios(Set<TaFuncionario> taFuncionarios) {
        this.taFuncionarios = taFuncionarios;
    }




}


