package model;
// Generated 07/10/2017 10:54:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbReuniao generated by hbm2java
 */
@Entity
@Table(name="tb_reuniao"
    ,catalog="ata_reuniao"
)
public class TbReuniao  implements java.io.Serializable {


     private Integer idtReuniao;
     private TbProjeto tbProjeto;
     private String nmeLocalReuniao;
     private String txtObjReuniao;
     private Date dtaReuniao;
     private Date dtaProxReuniao;
     private Set<TbPauta> tbPautas = new HashSet<TbPauta>(0);
     private Set<TbAssunto> tbAssuntos = new HashSet<TbAssunto>(0);
     private Set<TaParticipantes> taParticipanteses = new HashSet<TaParticipantes>(0);

    public TbReuniao() {
    }

	
    public TbReuniao(String nmeLocalReuniao, String txtObjReuniao, Date dtaReuniao) {
        this.nmeLocalReuniao = nmeLocalReuniao;
        this.txtObjReuniao = txtObjReuniao;
        this.dtaReuniao = dtaReuniao;
    }
    public TbReuniao(TbProjeto tbProjeto, String nmeLocalReuniao, String txtObjReuniao, Date dtaReuniao, Date dtaProxReuniao, Set<TbPauta> tbPautas, Set<TbAssunto> tbAssuntos, Set<TaParticipantes> taParticipanteses) {
       this.tbProjeto = tbProjeto;
       this.nmeLocalReuniao = nmeLocalReuniao;
       this.txtObjReuniao = txtObjReuniao;
       this.dtaReuniao = dtaReuniao;
       this.dtaProxReuniao = dtaProxReuniao;
       this.tbPautas = tbPautas;
       this.tbAssuntos = tbAssuntos;
       this.taParticipanteses = taParticipanteses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_reuniao", unique=true, nullable=false)
    public Integer getIdtReuniao() {
        return this.idtReuniao;
    }
    
    public void setIdtReuniao(Integer idtReuniao) {
        this.idtReuniao = idtReuniao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_projeto")
    public TbProjeto getTbProjeto() {
        return this.tbProjeto;
    }
    
    public void setTbProjeto(TbProjeto tbProjeto) {
        this.tbProjeto = tbProjeto;
    }

    
    @Column(name="nme_local_reuniao", nullable=false, length=45)
    public String getNmeLocalReuniao() {
        return this.nmeLocalReuniao;
    }
    
    public void setNmeLocalReuniao(String nmeLocalReuniao) {
        this.nmeLocalReuniao = nmeLocalReuniao;
    }

    
    @Column(name="txt_obj_reuniao", nullable=false, length=65535)
    public String getTxtObjReuniao() {
        return this.txtObjReuniao;
    }
    
    public void setTxtObjReuniao(String txtObjReuniao) {
        this.txtObjReuniao = txtObjReuniao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_reuniao", nullable=false, length=10)
    public Date getDtaReuniao() {
        return this.dtaReuniao;
    }
    
    public void setDtaReuniao(Date dtaReuniao) {
        this.dtaReuniao = dtaReuniao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_prox_reuniao", length=10)
    public Date getDtaProxReuniao() {
        return this.dtaProxReuniao;
    }
    
    public void setDtaProxReuniao(Date dtaProxReuniao) {
        this.dtaProxReuniao = dtaProxReuniao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbReuniao")
    public Set<TbPauta> getTbPautas() {
        return this.tbPautas;
    }
    
    public void setTbPautas(Set<TbPauta> tbPautas) {
        this.tbPautas = tbPautas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbReuniao")
    public Set<TbAssunto> getTbAssuntos() {
        return this.tbAssuntos;
    }
    
    public void setTbAssuntos(Set<TbAssunto> tbAssuntos) {
        this.tbAssuntos = tbAssuntos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbReuniao")
    public Set<TaParticipantes> getTaParticipanteses() {
        return this.taParticipanteses;
    }
    
    public void setTaParticipanteses(Set<TaParticipantes> taParticipanteses) {
        this.taParticipanteses = taParticipanteses;
    }




}


