package model;
// Generated 07/10/2017 10:54:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbFuncao generated by hbm2java
 */
@Entity
@Table(name="tb_funcao"
    ,catalog="ata_reuniao"
)
public class TbFuncao  implements java.io.Serializable {


     private Integer idtFuncao;
     private String nmeFuncao;
     private Set<TaParticipantes> taParticipanteses = new HashSet<TaParticipantes>(0);

    public TbFuncao() {
    }

	
    public TbFuncao(String nmeFuncao) {
        this.nmeFuncao = nmeFuncao;
    }
    public TbFuncao(String nmeFuncao, Set<TaParticipantes> taParticipanteses) {
       this.nmeFuncao = nmeFuncao;
       this.taParticipanteses = taParticipanteses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_funcao", unique=true, nullable=false)
    public Integer getIdtFuncao() {
        return this.idtFuncao;
    }
    
    public void setIdtFuncao(Integer idtFuncao) {
        this.idtFuncao = idtFuncao;
    }

    
    @Column(name="nme_funcao", nullable=false, length=45)
    public String getNmeFuncao() {
        return this.nmeFuncao;
    }
    
    public void setNmeFuncao(String nmeFuncao) {
        this.nmeFuncao = nmeFuncao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbFuncao")
    public Set<TaParticipantes> getTaParticipanteses() {
        return this.taParticipanteses;
    }
    
    public void setTaParticipanteses(Set<TaParticipantes> taParticipanteses) {
        this.taParticipanteses = taParticipanteses;
    }




}


