package model;
// Generated 07/10/2017 10:54:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbPauta generated by hbm2java
 */
@Entity
@Table(name="tb_pauta"
    ,catalog="ata_reuniao"
)
public class TbPauta  implements java.io.Serializable {


     private Integer idtPauta;
     private TbReuniao tbReuniao;
     private int ordPauta;
     private Date hraTempoPauta;
     private String txtPauta;
     private Set<TbAssunto> tbAssuntos = new HashSet<TbAssunto>(0);

    public TbPauta() {
    }

	
    public TbPauta(TbReuniao tbReuniao, int ordPauta, Date hraTempoPauta, String txtPauta) {
        this.tbReuniao = tbReuniao;
        this.ordPauta = ordPauta;
        this.hraTempoPauta = hraTempoPauta;
        this.txtPauta = txtPauta;
    }
    public TbPauta(TbReuniao tbReuniao, int ordPauta, Date hraTempoPauta, String txtPauta, Set<TbAssunto> tbAssuntos) {
       this.tbReuniao = tbReuniao;
       this.ordPauta = ordPauta;
       this.hraTempoPauta = hraTempoPauta;
       this.txtPauta = txtPauta;
       this.tbAssuntos = tbAssuntos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_pauta", unique=true, nullable=false)
    public Integer getIdtPauta() {
        return this.idtPauta;
    }
    
    public void setIdtPauta(Integer idtPauta) {
        this.idtPauta = idtPauta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_reuniao", nullable=false)
    public TbReuniao getTbReuniao() {
        return this.tbReuniao;
    }
    
    public void setTbReuniao(TbReuniao tbReuniao) {
        this.tbReuniao = tbReuniao;
    }

    
    @Column(name="ord_pauta", nullable=false)
    public int getOrdPauta() {
        return this.ordPauta;
    }
    
    public void setOrdPauta(int ordPauta) {
        this.ordPauta = ordPauta;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="hra_tempo_pauta", nullable=false, length=19)
    public Date getHraTempoPauta() {
        return this.hraTempoPauta;
    }
    
    public void setHraTempoPauta(Date hraTempoPauta) {
        this.hraTempoPauta = hraTempoPauta;
    }

    
    @Column(name="txt_pauta", nullable=false, length=65535)
    public String getTxtPauta() {
        return this.txtPauta;
    }
    
    public void setTxtPauta(String txtPauta) {
        this.txtPauta = txtPauta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbPauta")
    public Set<TbAssunto> getTbAssuntos() {
        return this.tbAssuntos;
    }
    
    public void setTbAssuntos(Set<TbAssunto> tbAssuntos) {
        this.tbAssuntos = tbAssuntos;
    }




}


