package model;
// Generated 07/10/2017 10:54:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbProjeto generated by hbm2java
 */
@Entity
@Table(name="tb_projeto"
    ,catalog="ata_reuniao"
)
public class TbProjeto  implements java.io.Serializable {


     private Integer idtProjeto;
     private String nmeProjeto;
     private boolean flgAtivo;
     private Set<TbReuniao> tbReuniaos = new HashSet<TbReuniao>(0);

    public TbProjeto() {
    }

	
    public TbProjeto(String nmeProjeto, boolean flgAtivo) {
        this.nmeProjeto = nmeProjeto;
        this.flgAtivo = flgAtivo;
    }
    public TbProjeto(String nmeProjeto, boolean flgAtivo, Set<TbReuniao> tbReuniaos) {
       this.nmeProjeto = nmeProjeto;
       this.flgAtivo = flgAtivo;
       this.tbReuniaos = tbReuniaos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_projeto", unique=true, nullable=false)
    public Integer getIdtProjeto() {
        return this.idtProjeto;
    }
    
    public void setIdtProjeto(Integer idtProjeto) {
        this.idtProjeto = idtProjeto;
    }

    
    @Column(name="nme_projeto", nullable=false, length=45)
    public String getNmeProjeto() {
        return this.nmeProjeto;
    }
    
    public void setNmeProjeto(String nmeProjeto) {
        this.nmeProjeto = nmeProjeto;
    }

    
    @Column(name="flg_ativo", nullable=false)
    public boolean isFlgAtivo() {
        return this.flgAtivo;
    }
    
    public void setFlgAtivo(boolean flgAtivo) {
        this.flgAtivo = flgAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbProjeto")
    public Set<TbReuniao> getTbReuniaos() {
        return this.tbReuniaos;
    }
    
    public void setTbReuniaos(Set<TbReuniao> tbReuniaos) {
        this.tbReuniaos = tbReuniaos;
    }




}


